services:
  btrfs-commander:
    build: .
    container_name: btrfs_web_ui
    privileged: true
    environment:
      - TZ=UTC
      # - PASSWORD=admin  # Uncomment to enable login
    volumes:
      - /home/jayesh/vm/:/host
      - ./data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped
